#---------------------------------------------------#
## 这份文件是clashX的基础配置文件，请尽量新建配置文件进行修改。
## ！！！只有这份文件的端口设置会随ClashX启动生效
#---------------------------------------------------#

# HTTP 代理端口
port: 7890

# SOCKS5 代理端口
socks-port: 7891

# Linux 和 macOS 的 redir 代理端口 (如需使用此功能，请取消注释)
redir-port: 7892

# 允许局域网的连接（可用来共享代理）
allow-lan: true

# 规则模式：Global（全局代理）/ Rule（规则） / Script(腳本) / Direct（全局直连）
mode: Rule

# 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / info / warning / error / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: info

# clash 的 RESTful API
external-controller: '0.0.0.0:9090'


# 您可以将静态网页资源（如 clash-dashboard）放置在一个目录中，clash 将会服务于 `${API}/ui`
# 参数应填写配置目录的相对路径或绝对路径。
# external-ui: folder

# RESTful API 的口令 (可选)
secret: ""

# DNS 设置

dns:
 enable: true
 ipv6: true
 listen: 0.0.0.0:53
 enhanced-mode: redir-host
 nameserver:
  - 8.8.8.8
  - 119.29.29.29
  - 223.5.5.5
  - https://rubyfish.cn/dns-query
 fallback:
  - https://cloudflare-dns.com/dns-query
  - tls://1.0.0.1:853
  - https://dns.google/dns-query#

# 代理节点
proxy-providers:

  China:
    type: http
    path: ./Server/China.yaml # 这里文件名称需要与订阅节点名称一样
    url: http://storage.live.com/items/C2597865DFB605BB!62098?authkey=AIzYW9ov5dkLmZc # 这里填写订阅链接
    interval: 3600
    health-check:
        enable: true
        url: http://www.gstatic.com/generate_204
        interval: 300

  Hong Kong:
    type: http
    path: ./Server/Hong Kong.yaml # 这里文件名称需要与订阅节点名称一样
    url: https://sub.hthome.tk/api/v1/client/subscribe?token=f4b065ab00e89a25e51e6bedbddf1fa9 # 这里填写订阅链接
    interval: 3600
    filter: '香港'
    health-check:
        enable: true
        url: http://www.gstatic.com/generate_204
        interval: 300

  Tai Wan:
    type: http
    path: ./Server/Tai Wan.yaml # 这里文件名称需要与订阅节点名称一样
    url: https://sub.hthome.tk/api/v1/client/subscribe?token=f4b065ab00e89a25e51e6bedbddf1fa9 # 这里填写订阅链接
    interval: 3600
    filter: '台湾'
    health-check:
        enable: true
        url: http://www.gstatic.com/generate_204
        interval: 300
        
  Japan:
    type: http
    path: ./Server/Japan.yaml # 这里文件名称需要与订阅节点名称一样
    url: https://sub.hthome.tk/api/v1/client/subscribe?token=f4b065ab00e89a25e51e6bedbddf1fa9 # 这里填写订阅链接
    interval: 3600
    filter: '日本'
    health-check:
        enable: true
        url: http://www.gstatic.com/generate_204
        interval: 300

  United States:
    type: http
    path: ./Server/United States.yaml # 这里文件名称需要与订阅节点名称一样
    url: https://sub.hthome.tk/api/v1/client/subscribe?token=f4b065ab00e89a25e51e6bedbddf1fa9 # 这里填写订阅链接
    interval: 3600
    filter: '美国'
    health-check:
        enable: true
        url: http://www.gstatic.com/generate_204
        interval: 300

  Korea:
    type: http
    path: ./Server/Korea.yaml # 这里文件名称需要与订阅节点名称一样
    url: https://sub.hthome.tk/api/v1/client/subscribe?token=f4b065ab00e89a25e51e6bedbddf1fa9 # 这里填写订阅链接
    interval: 3600
    filter: '韩国'
    health-check:
        enable: true
        url: http://www.gstatic.com/generate_204
        interval: 300
        
  Singapore:
    type: http
    path: ./Server/Singapore.yaml # 这里文件名称需要与订阅节点名称一样
    url: https://sub.hthome.tk/api/v1/client/subscribe?token=f4b065ab00e89a25e51e6bedbddf1fa9 # 这里填写订阅链接
    interval: 3600
    filter: '新加坡'
    health-check:
        enable: true
        url: http://www.gstatic.com/generate_204
        interval: 300  
        
  hentaihome:
    type: http
    path: ./Server/hentaihome.yaml # 这里文件名称需要与订阅节点名称一样
    url: https://sub.hthome.tk/api/v1/client/subscribe?token=f4b065ab00e89a25e51e6bedbddf1fa9 # 这里填写订阅链接
    interval: 3600
    health-check:
        enable: true
        url: http://www.gstatic.com/generate_204
        interval: 300 
        

# 代理组策略
proxy-groups:

# 策略组说明

# 「Proxy」是代理规则策略，它可以指定为某个节点或嵌套一个其他策略组，如：「url-test」（自动测试）、「Fallback」或「load-balance」（负载均衡）的策略组
 
- { name: "StreamingSE", type: select, use: ["Tai Wan","Hong Kong","China"]}
- { name: "CMedia", type: select, proxies: ["DIRECT"], use: ["China"]}
- { name: "China", type: select, proxies: ["DIRECT"], use: ["China"]}
- { name: "Speedtest", type: select, proxies: ["DIRECT","Proxy"]} 
- { name: "Steam", type: select, proxies: ["DIRECT","Proxy"]}
- { name: "Tencent", type: select, proxies: ["DIRECT"], use: ["China"]} 
- { name: "MATCH", type: select, proxies: ["DIRECT","Proxy"]}
- { name: "WeChat", type: select, proxies: ["DIRECT"], use: ["China"]}

# 分流规则  
rules:
  - RULE-SET,AdBlock,REJECT 
  - RULE-SET,CMedia,CMedia
  - RULE-SET,Speedtest,Speedtest
  - RULE-SET,Steam,Steam 
  - RULE-SET,Tencent,Tencent
  - RULE-SET,WeChat,WeChat
  - RULE-SET,StreamingSE,StreamingSE
  - RULE-SET,China,China
  - RULE-SET,ChinaIP,China
  - DOMAIN-SUFFIX,live.cn,CMedia
  
  # GeoIP China
  - GEOIP,CN,CMedia
  - MATCH,MATCH

rule-providers:

  AdBlock: {type: http, behavior: classical, path: ./Filter/AdBlock, url: https://cdn.jsdelivr.net/gh/Semporia/Clash-X@master/Filter/AdBlock.yaml, interval: 3600}
  CMedia: {type: http, behavior: classical, path: ./Filter/CMedia, url: https://raw.githubusercontent.com/prprinu/ClashX-Pro/master/Filter/CMedia.yaml, interval: 3600}
  Steam: {type: http, behavior: classical, path: ./Filter/Steam, url: https://cdn.jsdelivr.net/gh/Semporia/Clash-X@master/Filter/Steam.yaml, interval: 3600}
  Tencent: {type: http, behavior: classical, path: ./Filter/Tencent, url: https://cdn.jsdelivr.net/gh/Semporia/Clash-X@master/Filter/Tencent.yaml, interval: 3600}
  WeChat: {type: http, behavior: classical, path: ./Filter/WeChat, url: https://raw.githubusercontent.com/prprinu/ClashX-Pro/master/Filter/WeChat.yaml, interval: 3600}
  Speedtest: {type: http, behavior: classical, path: ./Filter/Speedtest, url: https://cdn.jsdelivr.net/gh/Semporia/Clash-X@master/Filter/Speedtest.yaml, interval: 3600}

  StreamingSE:
    type: http
    behavior: classical
    path: ./RuleSet/StreamingMedia/StreamingSE.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/StreamingSE.yaml
    interval: 86400
  
  China:
    type: http
    behavior: classical
    path: ./RuleSet/China.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/China.yaml
    interval: 86400
    
  ChinaIP:
    type: http
    behavior: ipcidr
    path: ./RuleSet/Extra/ChinaIP.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Extra/ChinaIP.yaml
    interval: 86400
